In [45]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

#Load dataset
digits = datasets.load_digits()
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [47]:
# print the names of the 13 features
# print the label type
# print data(feature)shape
print("\nLabels:", np.unique(digits.target_names))

print(digits.data.shape)
print(digits.target.shape)


Labels: [0 1 2 3 4 5 6 7 8 9]
(1797, 64)
(1797,)


In [48]:
#import the necessary module
from sklearn.model_selection import train_test_split

#split data set into train and test sets
X_train, X_test, y_train, y_test = train_test_split( 
    digits.data, digits.target, test_size = 0.35, random_state = 28)

In [49]:
#Create a Decision Tree Classifier (using Gini)
#Train the model using the training sets
clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 26,max_depth=7, min_samples_leaf=26)

clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=26, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=26, splitter='best')

In [50]:
# Predict the classes of test data
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
[8 8 2 0 2 8 8 2 8 7 6 2 9 7 5 3 1 1 6 9 2 9 1 8 7 6 1 6 7 1 6 5 8 7 2 8 6
 1 7 1 2 8 4 8 3 1 9 2 7 5 5 4 8 8 0 2 9 8 4 0 3 9 5 6 4 8 3 8 0 8 2 0 7 7
 8 9 2 6 8 5 1 1 4 3 1 5 0 2 1 6 4 9 0 4 3 3 9 6 1 0 0 9 1 4 9 2 2 7 9 2 9
 0 2 0 2 0 2 1 4 2 0 9 2 5 5 5 2 9 0 8 2 1 8 3 7 6 0 4 8 9 5 2 9 1 3 2 4 0
 8 4 9 3 2 7 5 6 2 8 0 0 4 2 9 4 9 2 1 7 9 5 6 7 2 4 7 4 8 0 3 4 3 8 4 1 6
 0 8 9 5 4 6 2 2 9 0 9 3 2 2 5 2 3 8 1 2 6 6 2 4 8 4 1 4 9 6 1 1 5 2 1 1 2
 3 6 5 2 7 8 5 8 8 5 2 4 7 0 6 0 6 9 0 1 5 7 0 6 6 7 9 7 9 8 2 2 0 2 9 2 8
 4 3 3 9 3 1 7 2 2 6 0 4 1 8 6 0 9 8 4 0 1 0 1 9 0 3 8 2 8 2 4 2 2 9 2 6 4
 2 8 7 1 4 3 6 2 9 4 6 4 8 4 1 7 3 9 6 2 0 4 2 6 4 9 7 9 9 7 3 9 8 5 0 1 4
 1 9 1 9 0 3 4 4 1 0 5 1 9 8 3 4 4 5 9 7 1 3 2 2 2 3 3 7 6 6 4 9 2 3 2 9 4
 1 5 7 3 6 0 9 0 2 0 0 5 2 3 8 3 9 8 2 5 4 1 9 9 9 0 1 1 3 7 9 8 0 5 0 6 4
 4 1 6 2 6 5 1 8 5 2 0 4 8 2 5 8 4 7 4 7 4 1 8 8 9 1 8 0 0 4 8 2 2 9 9 8 3
 5 8 2 9 3 8 5 9 8 5 4 4 8 3 2 8 9 8 7 4 4 5 5 2 1 8 7 7 7 9 7 9 5 4 6 8 7
 2 9 4 

In [51]:
# Model Accuracy
from sklearn import metrics
print("Confusion Matrix: ",
        metrics.confusion_matrix(y_test, y_pred))
print ("Accuracy : ",
    metrics.accuracy_score(y_test,y_pred)*100)
print("Report : ",
    metrics.classification_report(y_test, y_pred))

Confusion Matrix:  [[55  0  0  0  0  0  0  0  0  0]
 [ 0 40  3  3  9  0  0  0  3 10]
 [ 0  2 56  1  2  0  3  0  1  0]
 [ 0  4 13 37  0  1  0  3  6  1]
 [ 3  2  4  0 51  0  0  0  0  8]
 [ 0  1  3  0  1 46  0  0  0  6]
 [ 3  1  1  0  8  0 47  0  0  0]
 [ 0  0 12  0  0  0  0 43  5  6]
 [ 1  5  3  1  1  1  0  0 51  6]
 [ 2  1  1  2  0  3  0  0  7 40]]
Accuracy :  74.0858505564388
Report :                precision    recall  f1-score   support

           0       0.86      1.00      0.92        55
           1       0.71      0.59      0.65        68
           2       0.58      0.86      0.70        65
           3       0.84      0.57      0.68        65
           4       0.71      0.75      0.73        68
           5       0.90      0.81      0.85        57
           6       0.94      0.78      0.85        60
           7       0.93      0.65      0.77        66
           8       0.70      0.74      0.72        69
           9       0.52      0.71      0.60        56

    accuracy   